name: torch
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.9
  - numpy=1.21.*
  - pip
  - pandas
  - pytorch::pytorch>=1.11.0,<1.12.0
  - pytorch:torchvision>=0.12.0,<0.13.0
  - pytorch::torchaudio>=0.11.0,<0.12.0
  - cudatoolkit
  - pip:
    - pytest
    - pytorch_lightning>=1.5.0,<1.6.0
    - matplotlib
    - mlflow